In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [4]:
p = [1096.5, 596.95, 896.95]

In [5]:
c = 30.1

In [6]:
prices = np.array(p)

In [7]:
prices

array([1096.5 ,  596.95,  896.95])

In [8]:
print(prices)

[1096.5   596.95  896.95]


In [9]:
prices * c

array([33004.65 , 17968.195, 26998.195])