In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randn(100)

In [3]:
A

array([-0.77308467,  1.30440821,  1.32650772, -0.57775449,  0.495755  ,
       -2.34622131, -0.31425829,  0.40957395, -1.24449604,  0.30269577,
       -0.13119883, -0.31020588,  0.1716635 , -1.06105052,  1.98088609,
       -0.31294528, -0.33711052, -1.46902886,  0.52648489, -1.19146915,
        0.70426653, -0.12258775, -1.06024435, -1.61828226,  0.11051661,
       -0.33951818, -1.18585984, -0.66187119, -1.26444062,  2.3230379 ,
       -0.02448242, -0.71857606,  0.94057335,  0.64196521,  0.53024042,
        0.47959842,  1.30792957, -1.41951001,  0.80856259, -0.56320927,
       -2.17748062,  1.38599817, -1.25774052, -2.16701848,  0.01990397,
        0.28779847,  0.30231553, -0.67608542, -0.56637442, -0.13916187,
        0.1196705 ,  0.60385945,  0.78453319,  0.20247641, -0.43176981,
        0.07470172, -0.19064659,  0.16032851,  0.16773924,  1.22244306,
        0.54482706,  1.15441767,  1.5296443 ,  1.38913122, -0.91532499,
       -0.35851292, -0.45599019, -2.15328122,  0.20850349, -0.60

In [4]:
A = 10*A +50

In [5]:
A

array([42.26915329, 63.04408211, 63.26507717, 44.22245507, 54.95755003,
       26.53778694, 46.85741714, 54.09573948, 37.55503961, 53.02695766,
       48.68801167, 46.89794123, 51.716635  , 39.38949476, 69.8088609 ,
       46.87054724, 46.6288948 , 35.30971139, 55.26484889, 38.08530847,
       57.0426653 , 48.77412253, 39.39755655, 33.81717739, 51.10516608,
       46.60481822, 38.14140159, 43.38128814, 37.35559378, 73.23037899,
       49.75517585, 42.81423945, 59.40573354, 56.41965214, 55.30240416,
       54.79598419, 63.07929568, 35.80489988, 58.08562589, 44.36790733,
       28.22519376, 63.85998175, 37.42259484, 28.32981519, 50.19903971,
       52.87798472, 53.02315529, 43.23914576, 44.33625577, 48.60838127,
       51.19670504, 56.03859451, 57.84533193, 52.02476411, 45.6823019 ,
       50.74701717, 48.09353411, 51.60328505, 51.67739238, 62.22443063,
       55.44827057, 61.54417672, 65.29644304, 63.8913122 , 40.84675014,
       46.41487083, 45.44009809, 28.46718776, 52.08503489, 43.95

In [6]:
A.shape

(100,)

In [7]:
A.shape = (5, 20)

In [8]:
A

array([[42.26915329, 63.04408211, 63.26507717, 44.22245507, 54.95755003,
        26.53778694, 46.85741714, 54.09573948, 37.55503961, 53.02695766,
        48.68801167, 46.89794123, 51.716635  , 39.38949476, 69.8088609 ,
        46.87054724, 46.6288948 , 35.30971139, 55.26484889, 38.08530847],
       [57.0426653 , 48.77412253, 39.39755655, 33.81717739, 51.10516608,
        46.60481822, 38.14140159, 43.38128814, 37.35559378, 73.23037899,
        49.75517585, 42.81423945, 59.40573354, 56.41965214, 55.30240416,
        54.79598419, 63.07929568, 35.80489988, 58.08562589, 44.36790733],
       [28.22519376, 63.85998175, 37.42259484, 28.32981519, 50.19903971,
        52.87798472, 53.02315529, 43.23914576, 44.33625577, 48.60838127,
        51.19670504, 56.03859451, 57.84533193, 52.02476411, 45.6823019 ,
        50.74701717, 48.09353411, 51.60328505, 51.67739238, 62.22443063],
       [55.44827057, 61.54417672, 65.29644304, 63.8913122 , 40.84675014,
        46.41487083, 45.44009809, 28.46718776, 5

In [9]:
A.reshape(100, 1)

array([[42.26915329],
       [63.04408211],
       [63.26507717],
       [44.22245507],
       [54.95755003],
       [26.53778694],
       [46.85741714],
       [54.09573948],
       [37.55503961],
       [53.02695766],
       [48.68801167],
       [46.89794123],
       [51.716635  ],
       [39.38949476],
       [69.8088609 ],
       [46.87054724],
       [46.6288948 ],
       [35.30971139],
       [55.26484889],
       [38.08530847],
       [57.0426653 ],
       [48.77412253],
       [39.39755655],
       [33.81717739],
       [51.10516608],
       [46.60481822],
       [38.14140159],
       [43.38128814],
       [37.35559378],
       [73.23037899],
       [49.75517585],
       [42.81423945],
       [59.40573354],
       [56.41965214],
       [55.30240416],
       [54.79598419],
       [63.07929568],
       [35.80489988],
       [58.08562589],
       [44.36790733],
       [28.22519376],
       [63.85998175],
       [37.42259484],
       [28.32981519],
       [50.19903971],
       [52

In [11]:
A = A.reshape(100, 1)

In [12]:
A

array([[42.26915329],
       [63.04408211],
       [63.26507717],
       [44.22245507],
       [54.95755003],
       [26.53778694],
       [46.85741714],
       [54.09573948],
       [37.55503961],
       [53.02695766],
       [48.68801167],
       [46.89794123],
       [51.716635  ],
       [39.38949476],
       [69.8088609 ],
       [46.87054724],
       [46.6288948 ],
       [35.30971139],
       [55.26484889],
       [38.08530847],
       [57.0426653 ],
       [48.77412253],
       [39.39755655],
       [33.81717739],
       [51.10516608],
       [46.60481822],
       [38.14140159],
       [43.38128814],
       [37.35559378],
       [73.23037899],
       [49.75517585],
       [42.81423945],
       [59.40573354],
       [56.41965214],
       [55.30240416],
       [54.79598419],
       [63.07929568],
       [35.80489988],
       [58.08562589],
       [44.36790733],
       [28.22519376],
       [63.85998175],
       [37.42259484],
       [28.32981519],
       [50.19903971],
       [52