In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
grades = np.array([[85, 70, 82], [75, 92, 85], [66, 67, 64], [84, 61, 95]])

In [3]:
grades

array([[85, 70, 82],
       [75, 92, 85],
       [66, 67, 64],
       [84, 61, 95]])

In [4]:
weights = np.array([0.3, 0.4, 0.3])

In [5]:
np.dot(grades, weights)

array([78.1, 84.8, 65.8, 78.1])

In [6]:
L = np.array([3, 5, 7, 9])

In [8]:
L* 3

array([ 9, 15, 21, 27])